"""campagnes de mise a jour (remplacent le pulse hebdomadaire)

Revision ID: 32e64e77ea62
Revises: 97b450c1a6f9
Create Date: 2026-10-03 13:19:43.987812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32e64e77ea62'
down_revision: Union[str, Sequence[str], None] = '97b450c1a6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('team_ids', sa.JSON(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closes_on', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_org_id'), 'campaigns', ['org_id'], unique=False)
    op.create_table('campaign_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('done_items', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('active_tools', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('usecases', sa.Integer(), nullable=False),
    sa.Column('adopted', sa.Integer(), nullable=False),
    sa.Column('minutes_saved', sa.Integer(), nullable=False),
    sa.Column('usage_level', sa.Integer(), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('blockers', sa.JSON(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id')
    )
    op.create_index(op.f('ix_campaign_participants_campaign_id'), 'campaign_participants', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_participants_user_id'), 'campaign_participants', ['user_id'], unique=False)
    op.drop_index(op.f('ix_pulses_org_id'), table_name='pulses')
    op.drop_index(op.f('ix_pulses_user_id'), table_name='pulses')
    op.drop_index(op.f('ix_pulses_week'), table_name='pulses')
    op.drop_table('pulses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('usage_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hours_saved', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('satisfaction', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blockers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('pulses_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('pulses_team_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('pulses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pulses_pkey')),
    sa.UniqueConstraint('user_id', 'week', name=op.f('pulses_user_id_week_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pulses_week'), 'pulses', ['week'], unique=False)
    op.create_index(op.f('ix_pulses_user_id'), 'pulses', ['user_id'], unique=False)
    op.create_index(op.f('ix_pulses_org_id'), 'pulses', ['org_id'], unique=False)
    op.drop_index(op.f('ix_campaign_participants_user_id'), table_name='campaign_participants')
    op.drop_index(op.f('ix_campaign_participants_campaign_id'), table_name='campaign_participants')
    op.drop_table('campaign_participants')
    op.drop_index(op.f('ix_campaigns_org_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
