"""English content for the demo organisation (same shape as scripts/demo_data.py).

Used by `python -m scripts.admin demo --lang en`: same generator, same figures,
only the texts change. Fictional data.
"""

from __future__ import annotations

DEMO_NAME = "Acme Industries (demo)"
DEMO_DOMAIN = "demo-en.acme.test"
ADMIN_NAME = "Alex Morgan"

# team → (adoption propensity 0..1, jobs, favourite tools)
TEAMS: dict[str, tuple[float, list[str], list[str]]] = {
    "Leadership": (
        0.6,
        ["Chief Executive Officer", "Chief Operating Officer", "Chief Financial Officer"],
        ["ChatGPT", "Microsoft Copilot", "Claude"],
    ),
    "Product": (
        0.72,
        ["Product manager", "Product designer", "Product owner"],
        ["Claude", "ChatGPT", "Notion AI", "Perplexity"],
    ),
    "Engineering": (
        0.86,
        ["Software engineer", "Software engineer", "Tech lead", "SRE"],
        ["GitHub Copilot", "Cursor", "Claude Code", "Claude", "ChatGPT"],
    ),
    "Data": (
        0.9,
        ["Data analyst", "Data scientist", "Data engineer"],
        ["Claude", "ChatGPT", "GitHub Copilot", "NotebookLM"],
    ),
    "Marketing": (
        0.76,
        ["Marketing manager", "Content manager", "Growth marketer"],
        ["ChatGPT", "Midjourney", "Claude", "Le Chat (Mistral)", "Perplexity"],
    ),
    "Sales": (
        0.46,
        ["Account executive", "Account manager", "Business developer"],
        ["ChatGPT", "Microsoft Copilot", "Perplexity"],
    ),
    "Customer Support": (
        0.6,
        ["Support specialist", "Support manager"],
        ["ChatGPT", "Microsoft Copilot", "Le Chat (Mistral)"],
    ),
    "HR": (
        0.36,
        ["HR business partner", "Recruiter", "Learning manager"],
        ["ChatGPT", "Microsoft Copilot"],
    ),
    "Finance": (
        0.4,
        ["Financial controller", "Accountant", "Financial analyst"],
        ["Microsoft Copilot", "ChatGPT", "Gemini"],
    ),
}
SIZES = {
    "Leadership": 3,
    "Product": 6,
    "Engineering": 9,
    "Data": 5,
    "Marketing": 6,
    "Sales": 7,
    "Customer Support": 6,
    "HR": 4,
    "Finance": 5,
}

FIRST = [
    "Olivia",
    "Liam",
    "Emma",
    "Noah",
    "Ava",
    "Ethan",
    "Sophia",
    "Lucas",
    "Mia",
    "Mason",
    "Amelia",
    "James",
    "Harper",
    "Benjamin",
    "Ella",
    "Daniel",
    "Grace",
    "Samuel",
    "Chloe",
    "Henry",
    "Zoe",
    "Omar",
    "Priya",
    "Mateo",
    "Aisha",
    "Leo",
    "Hannah",
    "Kenji",
    "Nora",
    "Diego",
    "Lily",
    "Ravi",
    "Sara",
    "Tom",
    "Yara",
    "Felix",
    "Maya",
    "Jonah",
    "Ines",
    "Owen",
    "Clara",
    "Isaac",
    "Leila",
    "Hugo",
    "Nina",
    "Adam",
    "Rosa",
    "Theo",
    "Alice",
    "Max",
]
LAST = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Martin",
    "Lopez",
    "Wilson",
    "Anderson",
    "Taylor",
    "Thomas",
    "Moore",
    "Jackson",
    "White",
    "Harris",
    "Clark",
    "Lewis",
    "Walker",
    "Young",
    "Patel",
    "Nguyen",
    "Khan",
    "Chen",
    "Rossi",
    "Silva",
    "Murphy",
    "Kelly",
    "Novak",
    "Fischer",
    "Okafor",
    "Haddad",
    "Larsen",
]

COMMENTS = [
    "I saved a lot of time on meeting notes.",
    "Still no Copilot licence, I have to use the free version.",
    "Not sure what we're allowed to paste in when it comes to customer data.",
    "Great for getting a document started, less so for numbers.",
    "We need prompt training tailored to our job.",
    "The Data team's use cases gave me lots of ideas.",
    "Busy week, no time to explore.",
    "Answers about our regulations are often wrong.",
    "Claude helps me a lot reviewing my specs.",
    "I'd like an approved tool to analyse Excel files.",
]

# (team, title, category, problem, solution, prompt, tools, minutes/week, risk)
USE_CASES = [
    (
        "Engineering",
        "Generate unit tests for an existing module",
        "code",
        "Writing tests for an old untested module takes days.",
        "I give the model the file and our test conventions, it drafts a first set of tests; "
        "I review, adjust the edge cases and run them.",
        "Here is a Python module and our pytest conventions. Write tests covering the happy "
        "path, errors and edge cases. Do not change the code under test.",
        ["Claude Code", "GitHub Copilot"],
        180,
        "low",
    ),
    (
        "Engineering",
        "Review a pull request before the human review",
        "code",
        "Reviews take time and still miss simple mistakes.",
        "Before asking for a review, I have the AI read the diff: likely bugs, naming, missing "
        "tests. The human review can then focus on architecture.",
        "Review this diff as a senior engineer. List the likely bugs first, then improvements, "
        "in order of importance.",
        ["Claude", "Cursor"],
        90,
        "low",
    ),
    (
        "Engineering",
        "Explain a production incident from the logs",
        "analyse",
        "Reading thousands of log lines during an incident.",
        "I paste the anonymised logs, the AI proposes a timeline and hypotheses that I check "
        "one by one.",
        "",
        ["Claude"],
        60,
        "medium",
    ),
    (
        "Data",
        "Write and document SQL queries",
        "analyse",
        "Business teams wait for extracts, and nobody documents the queries.",
        "I describe the need and the schema; the AI writes the query and an explanation. I check "
        "it on a sample.",
        "Here is the table schema (no data). Write the SQL query for: … Explain each join.",
        ["Claude", "ChatGPT"],
        150,
        "low",
    ),
    (
        "Data",
        "Summarise a dashboard for the executive committee",
        "synthese",
        "Turning 20 charts into three key messages every month.",
        "I provide the exported key figures, the AI drafts a summary that I edit.",
        "",
        ["Claude"],
        120,
        "medium",
    ),
    (
        "Product",
        "Turn user interview notes into insights",
        "synthese",
        "Ten interviews per sprint, pages of notes nobody uses.",
        "I paste the anonymised notes, the AI groups them by theme with quotes; I validate and "
        "prioritise.",
        "Group these interview notes by theme. For each theme: a one-sentence "
        "summary and 2 exact quotes.",
        ["Claude", "NotebookLM"],
        240,
        "medium",
    ),
    (
        "Product",
        "Draft a first version of a functional spec",
        "redaction",
        "The blank page for every new feature.",
        "I give the context, users and constraints; the AI proposes a spec outline and "
        "acceptance criteria that I complete.",
        "",
        ["Claude", "Notion AI"],
        120,
        "low",
    ),
    (
        "Marketing",
        "Turn an article into LinkedIn posts",
        "redaction",
        "Every article had to be rewritten by hand for each network.",
        "One article → 5 posts in our tone, which I review and adjust.",
        "Here is an article and three examples of our LinkedIn posts. Suggest 5 posts in the "
        "same tone, 600 characters max.",
        ["ChatGPT", "Claude"],
        150,
        "low",
    ),
    (
        "Marketing",
        "Illustrations for the blog",
        "creatif",
        "Generic and expensive stock images.",
        "Illustrations generated in our brand style, retouched by the designer.",
        "",
        ["Midjourney"],
        90,
        "medium",
    ),
    (
        "Marketing",
        "Weekly competitor watch",
        "recherche",
        "Tracking 10 competitors by hand took half a day.",
        "AI search with sources, a 10-line summary, links checked.",
        "",
        ["Perplexity"],
        120,
        "low",
    ),
    (
        "Sales",
        "Prepare a client meeting in 10 minutes",
        "recherche",
        "Walking into meetings without knowing the client's latest news.",
        "Research on the company (news, priorities, public contacts), then tailored discovery "
        "questions.",
        "",
        ["Perplexity", "ChatGPT"],
        90,
        "low",
    ),
    (
        "Sales",
        "Write follow-up emails after meetings",
        "redaction",
        "Meeting notes and follow-ups went out days late.",
        "From my notes, the AI drafts the follow-up email with next steps.",
        "",
        ["Microsoft Copilot"],
        60,
        "low",
    ),
    (
        "Customer Support",
        "Suggest replies to frequent tickets",
        "support",
        "60% of tickets are about the same questions.",
        "I provide the question and our knowledge base; the AI suggests a reply I personalise. "
        "Never customer data in a consumer tool.",
        "",
        ["Le Chat (Mistral)", "ChatGPT"],
        300,
        "medium",
    ),
    (
        "Customer Support",
        "Translate replies for international customers",
        "support",
        "Customers in German and Spanish, nobody on the team speaks those languages.",
        "Translation of our replies, quick check of the meaning.",
        "",
        ["ChatGPT"],
        90,
        "low",
    ),
    (
        "HR",
        "Write inclusive job ads",
        "redaction",
        "Job ads that were too long, with wording that put candidates off.",
        "The AI rewrites the ad in inclusive language and flags unnecessary requirements. "
        "Always checked by a human for bias.",
        "",
        ["ChatGPT"],
        60,
        "medium",
    ),
    (
        "HR",
        "Prepare an onboarding plan",
        "redaction",
        "Every manager improvised how they welcomed new hires.",
        "A 30-day onboarding outline per job, adapted then approved by managers.",
        "",
        ["Microsoft Copilot"],
        45,
        "low",
    ),
    (
        "Finance",
        "Explain budget variances",
        "analyse",
        "Commenting on each cost centre's variances every month.",
        "From the aggregated variance table (no personal data), the AI suggests comments that "
        "I complete.",
        "",
        ["Microsoft Copilot"],
        120,
        "high",
    ),
    (
        "Finance",
        "Complex Excel formulas",
        "automatisation",
        "Hours lost on nested formulas.",
        "I describe the calculation, the AI writes the formula and explains it.",
        "",
        ["Microsoft Copilot", "ChatGPT"],
        60,
        "low",
    ),
    (
        "Leadership",
        "Prepare an executive committee meeting",
        "synthese",
        "Reading all the pre-read documents the night before.",
        "Summary of the documents (company-approved tool), questions to ask, points to watch.",
        "",
        ["Microsoft Copilot", "Claude"],
        120,
        "high",
    ),
    (
        "Engineering",
        "Create tickets automatically from alerts",
        "automatisation",
        "Monitoring alerts were copied into tickets by hand.",
        "A small agent reads the alert and drafts a ticket with context and priority, approved "
        "by the on-call engineer.",
        "",
        ["Claude Code"],
        120,
        "medium",
    ),
    (
        "Product",
        "Write release notes",
        "redaction",
        "Translating technical tickets into customer language.",
        "Sprint tickets → clear release notes, reviewed by the product owner.",
        "",
        ["Claude"],
        60,
        "low",
    ),
    (
        "Data",
        "Clean a CSV file of leads",
        "automatisation",
        "Duplicates, phone formats, misspelt cities.",
        "The AI writes a pandas cleaning script; the file itself never goes into the tool.",
        "",
        ["ChatGPT", "GitHub Copilot"],
        90,
        "medium",
    ),
]

# (team, kind, text, anonymous, status, response)
FEEDBACKS = [
    (
        "Sales",
        "frein",
        "We don't have Copilot licences in the sales team, we make do.",
        False,
        "in_progress",
        "Licence request sent to IT, answer expected by the end of the month.",
    ),
    ("HR", "formation", "Training on good practices and risks would be useful.", True, "new", ""),
    (
        "Customer Support",
        "outil",
        "An assistant connected to our internal knowledge base would save a huge amount of time.",
        False,
        "new",
        "",
    ),
    (
        "Finance",
        "frein",
        "I don't know what we're allowed to put into these tools.",
        True,
        "done",
        "Usage policy published on the intranet, “Data” section.",
    ),
    (
        "Engineering",
        "idee",
        "Share our code review prompts in a common repository.",
        False,
        "done",
        "Done: see the use case “Review a pull request”.",
    ),
    (
        "Marketing",
        "idee",
        "Run a monthly workshop to share use cases across teams.",
        False,
        "in_progress",
        "First workshop on the 15th, registration open.",
    ),
    ("Product", "outil", "Access to Claude enterprise for internal documents.", False, "new", ""),
    ("Sales", "formation", "Concrete examples for our job, not generic advice.", True, "new", ""),
    (
        "Data",
        "autre",
        "Time saved would be more reliable if measured from Jira data.",
        False,
        "new",
        "",
    ),
    (
        "Customer Support",
        "frein",
        "Answers are sometimes wrong about our pricing.",
        True,
        "in_progress",
        "We're preparing a reference sheet to give as context.",
    ),
    ("HR", "frein", "Worried AI could be used to evaluate employees.", True, "new", ""),
    ("Finance", "outil", "Copilot in Excel for the whole team.", False, "new", ""),
]

MONTHS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]


def campaign_title(month: str) -> str:
    return f"AI check-in — {month}"


CAMPAIGN_MESSAGE = (
    "Please take 5 minutes to update your tools, your self-assessment and your use cases: "
    "this is how we measure the time saved and plan the right training. Thank you!"
)
